name: Mainnet-Schedule

on:
  schedule:
    - cron: '10 13 * * *' # post mainnet epoch for persistence
    - cron: '*/5 * * * *' # test


env:
  SMARTSTAKE_ACCESS_KEY: ${{ secrets.SMARTSTAKE_ACCESS_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

jobs:
  liquidstake-persistence-valset:
    if: github.event.schedule == '*/5 * * * *'
    environment: prod
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 24.x ]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run get data to make weights
        run: npm run smartstake-update-valset-weights-xprt
        env:
          FN: "GET_DATA"
          HOST_CHAIN: "persistence"
      - name: Run do txn
        run: npm run smartstake-update-valset-weights-xprt
        env:
          FN: "DO_TX"
          HOST_CHAIN: "persistence"
