name: Schedule

on:
  schedule:
    #    - cron: '00 12 * * *' # pre mainnet epoch
    - cron: '00 11 * * *' # post testnet epoch
    #    - cron: '0 10 * * *' # pre testnet epoch
    - cron: '0 */6 * * *' # every 6 hours

env:
  SMARTSTAKE_ACCESS_KEY: ${{ secrets.SMARTSTAKE_ACCESS_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

jobs:
#
#  liquidstakeibc-chihuahua-valset:
#    if: github.event.schedule == '0 */6 * * *'
#    environment: prod
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 16.x ]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#          cache-dependency-path: ./package-lock.json
#      - name: Install dependencies
#        run: npm ci
#      - name: Run get data to make weights
#        run: npm run update-stkatom-valset-weights
#        env:
#          FN: "GET_DATA"
#          HOST_CHAIN: "chihuahua"
#      - name: Run do txn
#        run: npm run update-stkatom-valset-weights
#        env:
#          FN: "DO_TX"
#          HOST_CHAIN: "chihuahua"

#  liquidstakeibc-cosmos-testnet-valset:
    #    if: github.event.schedule == '00 11 * * *'
#    if: github.event.schedule == '0 */6 * * *'
#    environment: prod
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 16.x ]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#          cache-dependency-path: ./package-lock.json
#      - name: Install dependencies
#        run: npm ci
#      - name: Run get data to make weights
#        run: npm run update-stkatom-valset-weights
#        env:
#          FN: "GET_DATA"
#          HOST_CHAIN: "cosmosTestnet"
#      - name: Run do txn
#        run: npm run update-stkatom-valset-weights
#        env:
#          FN: "DO_TX"
#          HOST_CHAIN: "cosmosTestnet"
#
#  liquidstakeibc-osmosis-testnet-valset:
    #    if: github.event.schedule == '00 11 * * *'
#    if: github.event.schedule == '0 */6 * * *'
#    environment: prod
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 16.x ]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#          cache-dependency-path: ./package-lock.json
#      - name: Install dependencies
#        run: npm ci
#      - name: Run get data to make weights
#        run: npm run update-stkatom-valset-weights
#        env:
#          FN: "GET_DATA"
#          HOST_CHAIN: "osmosisTestnet"
#      - name: Run do txn
#        run: npm run update-stkatom-valset-weights
#        env:
#          FN: "DO_TX"
#          HOST_CHAIN: "osmosisTestnet"
#
#  liquidstakeibc-persistence-testnet-valset:
#    #    if: github.event.schedule == '00 11 * * *'
#    if: github.event.schedule == '0 */6 * * *'
#    environment: prod
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [ 16.x ]
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'npm'
#          cache-dependency-path: ./package-lock.json
#      - name: Install dependencies
#        run: npm ci
#      - name: Run get data to make weights
#        run: npm run update-stkxprt-valset-weights
#        env:
#          FN: "GET_DATA"
#          HOST_CHAIN: "persistenceTestnet"
#      - name: Run do txn
#        run: npm run update-stkxprt-valset-weights
#        env:
#          FN: "DO_TX"
#          HOST_CHAIN: "persistenceTestnet"




