name: test-schedule-wf

on:
  pull_request:
    branches: [ main ]

jobs:
  liquidstakeibc-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run get data to make weights
        run: npm run update-stkatom-valset-weights
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
      - name: Run do txn
        run: npm run tx-update-stkatom-valset-weights
        env:
          MNEMONIC: ${{ secrets.MNEMONIC }}
